import argparse
import json
import re
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
CHANGELOG_PATH = ROOT / "CHANGELOG.md"
ENTRIES_PATH = ROOT / "changelog" / "entries"
RELEASES_PATH = ROOT / "changelog" / "releases.json"
GENERATED_NOTICE = "<!-- Generated by scripts/generate_changelog.py. Do not edit manually. -->\n\n"
SEMVER_PATTERN = re.compile(r"^[0-9]+\.[0-9]+\.[0-9]+$")
ENTRY_ID_PATTERN = re.compile(r"^[a-z0-9][a-z0-9-]{2,95}$")
TICKET_PATTERN = re.compile(r"^T[0-9]{4}$")
CATEGORY_LABELS = {
    "added": "Adicionado",
    "changed": "Alterado",
    "deprecated": "Obsoleto",
    "removed": "Removido",
    "fixed": "Corrigido",
    "security": "Seguranca",
}
ENTRY_FIELDS = {"id", "type", "summary", "details", "date", "version", "ticket"}


class ChangelogValidationError(ValueError):
    pass


class ChangelogOutdatedError(RuntimeError):
    pass


@dataclass(frozen=True)
class ChangelogEntry:
    entry_id: str
    entry_type: str
    summary: str
    details: tuple[str, ...]
    created_at: str
    version: str | None
    ticket: str | None


def require_text(value: Any, *, field: str, max_length: int) -> str:
    if not isinstance(value, str):
        raise ChangelogValidationError(f"{field} must be a string.")
    normalized = " ".join(value.split())
    if not normalized:
        raise ChangelogValidationError(f"{field} cannot be blank.")
    if len(normalized) > max_length:
        raise ChangelogValidationError(f"{field} must have at most {max_length} characters.")
    return normalized


def require_iso_date(value: Any, *, field: str) -> str:
    normalized = require_text(value, field=field, max_length=10)
    try:
        date.fromisoformat(normalized)
    except ValueError as exc:
        raise ChangelogValidationError(f"{field} must use YYYY-MM-DD.") from exc
    return normalized


def require_semver(value: Any, *, field: str) -> str:
    normalized = require_text(value, field=field, max_length=32)
    if SEMVER_PATTERN.fullmatch(normalized) is None:
        raise ChangelogValidationError(f"{field} must use semantic version MAJOR.MINOR.PATCH.")
    return normalized


def load_release_dates(releases_path: Path = RELEASES_PATH) -> dict[str, str]:
    payload = json.loads(releases_path.read_text(encoding="utf-8"))
    if set(payload) != {"releases"} or not isinstance(payload["releases"], list):
        raise ChangelogValidationError("releases.json must contain only a releases list.")

    releases = {}
    for release in payload["releases"]:
        if not isinstance(release, dict) or set(release) != {"version", "date"}:
            raise ChangelogValidationError("Each release must contain only version and date.")
        version = require_semver(release["version"], field="release.version")
        if version in releases:
            raise ChangelogValidationError(f"Duplicate release version: {version}.")
        releases[version] = require_iso_date(release["date"], field="release.date")
    return releases


def load_entry(entry_path: Path) -> ChangelogEntry:
    payload = json.loads(entry_path.read_text(encoding="utf-8"))
    if not isinstance(payload, dict):
        raise ChangelogValidationError(f"{entry_path.name} must contain an object.")

    unknown_fields = set(payload) - ENTRY_FIELDS
    required_fields = ENTRY_FIELDS - {"ticket"}
    missing_fields = required_fields - set(payload)
    if unknown_fields:
        raise ChangelogValidationError(f"{entry_path.name} has unknown fields: {sorted(unknown_fields)}.")
    if missing_fields:
        raise ChangelogValidationError(f"{entry_path.name} is missing fields: {sorted(missing_fields)}.")

    entry_id = require_text(payload["id"], field="id", max_length=96)
    if ENTRY_ID_PATTERN.fullmatch(entry_id) is None:
        raise ChangelogValidationError("id must use lowercase letters, numbers and hyphens.")

    entry_type = require_text(payload["type"], field="type", max_length=16)
    if entry_type not in CATEGORY_LABELS:
        raise ChangelogValidationError(f"Unsupported changelog type: {entry_type}.")

    if not isinstance(payload["details"], list) or len(payload["details"]) > 8:
        raise ChangelogValidationError("details must be a list with at most 8 items.")
    details = tuple(require_text(detail, field="details", max_length=240) for detail in payload["details"])

    version = payload["version"]
    if version is not None:
        version = require_semver(version, field="version")

    ticket = payload.get("ticket")
    if ticket is not None:
        ticket = require_text(ticket, field="ticket", max_length=5)
        if TICKET_PATTERN.fullmatch(ticket) is None:
            raise ChangelogValidationError("ticket must use T0000 format.")

    return ChangelogEntry(
        entry_id=entry_id,
        entry_type=entry_type,
        summary=require_text(payload["summary"], field="summary", max_length=240),
        details=details,
        created_at=require_iso_date(payload["date"], field="date"),
        version=version,
        ticket=ticket,
    )


def load_entries(
    *, entries_path: Path = ENTRIES_PATH, releases_path: Path = RELEASES_PATH
) -> tuple[list[ChangelogEntry], dict[str, str]]:
    releases = load_release_dates(releases_path)
    entries = []
    seen_ids = set()
    for entry_path in sorted(entries_path.glob("*.json")):
        entry = load_entry(entry_path)
        if entry.entry_id in seen_ids:
            raise ChangelogValidationError(f"Duplicate changelog entry id: {entry.entry_id}.")
        if entry.version is not None and entry.version not in releases:
            raise ChangelogValidationError(f"Entry {entry.entry_id} references unknown release {entry.version}.")
        seen_ids.add(entry.entry_id)
        entries.append(entry)
    return entries, releases


def semver_key(version: str) -> tuple[int, int, int]:
    major, minor, patch = (int(part) for part in version.split("."))
    return major, minor, patch


def render_entry(entry: ChangelogEntry) -> list[str]:
    ticket = f" [{entry.ticket}]" if entry.ticket else ""
    lines = [f"- {entry.summary}{ticket}"]
    lines.extend(f"  - {detail}" for detail in entry.details)
    return lines


def render_group(entries: list[ChangelogEntry]) -> list[str]:
    lines = []
    if not entries:
        return ["_Nenhuma alteracao registrada._"]

    for entry_type, label in CATEGORY_LABELS.items():
        typed_entries = [entry for entry in entries if entry.entry_type == entry_type]
        if not typed_entries:
            continue
        lines.extend([f"### {label}", ""])
        for entry in sorted(typed_entries, key=lambda item: (item.created_at, item.entry_id), reverse=True):
            lines.extend(render_entry(entry))
        lines.append("")
    return lines


def render_changelog(*, entries_path: Path = ENTRIES_PATH, releases_path: Path = RELEASES_PATH) -> str:
    entries, releases = load_entries(entries_path=entries_path, releases_path=releases_path)
    lines = [
        GENERATED_NOTICE.rstrip(),
        "",
        "# ORION Changelog",
        "",
        "Todas as alteracoes relevantes do ORION sao registradas neste arquivo gerado.",
        "A fonte autoritativa fica em `changelog/entries`.",
        "",
        "## [Nao lancado]",
        "",
    ]
    lines.extend(render_group([entry for entry in entries if entry.version is None]))

    for version in sorted(releases, key=semver_key, reverse=True):
        lines.extend(["", f"## [{version}] - {releases[version]}", ""])
        lines.extend(render_group([entry for entry in entries if entry.version == version]))

    return "\n".join(lines).rstrip() + "\n"


def generate_changelog(
    *,
    output_path: Path = CHANGELOG_PATH,
    entries_path: Path = ENTRIES_PATH,
    releases_path: Path = RELEASES_PATH,
    check: bool = False,
) -> Path:
    content = render_changelog(entries_path=entries_path, releases_path=releases_path)
    if check:
        if not output_path.exists() or output_path.read_text(encoding="utf-8") != content:
            try:
                display_path = output_path.relative_to(ROOT)
            except ValueError:
                display_path = output_path
            raise ChangelogOutdatedError(f"Generated changelog is outdated: {display_path}")
        return output_path

    output_path.write_text(content, encoding="utf-8")
    return output_path


def slugify(value: str) -> str:
    normalized = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return normalized[:56].rstrip("-") or "change"


def create_entry(
    *,
    entry_type: str,
    summary: str,
    details: list[str],
    ticket: str | None,
    entries_path: Path = ENTRIES_PATH,
    created_at: date | None = None,
) -> Path:
    if entry_type not in CATEGORY_LABELS:
        raise ChangelogValidationError(f"Unsupported changelog type: {entry_type}.")
    normalized_summary = require_text(summary, field="summary", max_length=240)
    normalized_details = [require_text(detail, field="details", max_length=240) for detail in details]
    if len(normalized_details) > 8:
        raise ChangelogValidationError("details must have at most 8 items.")
    if ticket is not None and TICKET_PATTERN.fullmatch(ticket) is None:
        raise ChangelogValidationError("ticket must use T0000 format.")

    entries_path.mkdir(parents=True, exist_ok=True)
    prefix = (created_at or date.today()).strftime("%Y%m%d")
    base_id = f"{prefix}-{slugify(normalized_summary)}"
    entry_id = base_id
    sequence = 2
    while (entries_path / f"{entry_id}.json").exists():
        entry_id = f"{base_id}-{sequence}"
        sequence += 1

    entry = {
        "id": entry_id,
        "type": entry_type,
        "summary": normalized_summary,
        "details": normalized_details,
        "date": (created_at or date.today()).isoformat(),
        "version": None,
    }
    if ticket is not None:
        entry["ticket"] = ticket

    entry_path = entries_path / f"{entry_id}.json"
    entry_path.write_text(json.dumps(entry, ensure_ascii=True, indent=2) + "\n", encoding="utf-8")
    return entry_path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail when CHANGELOG.md is outdated.")
    parser.add_argument("--new", choices=CATEGORY_LABELS, help="Create a new unreleased changelog fragment.")
    parser.add_argument("--summary", help="Short user-facing summary for a new fragment.")
    parser.add_argument("--detail", action="append", default=[], help="Supporting detail. Repeat when needed.")
    parser.add_argument("--ticket", help="Optional ORION ticket in T0000 format.")
    args = parser.parse_args()

    if args.check and args.new:
        raise SystemExit("--check and --new cannot be used together.")
    if args.new and not args.summary:
        raise SystemExit("--summary is required with --new.")
    if not args.new and (args.summary or args.detail or args.ticket):
        raise SystemExit("--summary, --detail and --ticket require --new.")

    try:
        if args.new:
            entry_path = create_entry(
                entry_type=args.new,
                summary=args.summary,
                details=args.detail,
                ticket=args.ticket,
            )
            print(f"Changelog entry created: {entry_path.relative_to(ROOT)}")
        changelog_path = generate_changelog(check=args.check)
    except (ChangelogOutdatedError, ChangelogValidationError) as exc:
        raise SystemExit(str(exc)) from exc

    action = "checked" if args.check else "generated"
    print(f"Changelog {action}: {changelog_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
