import argparse
import json
import sqlite3
import sys
from contextlib import closing
from importlib import import_module
from pathlib import Path
from typing import Any

from fastapi.routing import APIWebSocketRoute

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

EVENT_CATALOG = import_module("app.events").EVENT_CATALOG
app = import_module("app.main").app

WIKI_DIR = ROOT / "docs" / "wiki"
PLUGIN_SCHEMA_PATH = ROOT / "plugins" / "plugin.schema.json"
INSTALLED_PLUGINS_PATH = ROOT / "plugins" / "installed"
SCHEMA_PATH = ROOT / "database" / "schema.sql"
MIGRATIONS_PATH = ROOT / "database" / "migrations"
GENERATED_NOTICE = "<!-- Generated by scripts/generate_wiki.py. Do not edit manually. -->\n\n"


class WikiOutdatedError(RuntimeError):
    pass


def markdown_cell(value: Any) -> str:
    if value is None:
        return "-"
    return str(value).replace("|", "\\|").replace("\n", " ")


def schema_type(schema: dict[str, Any]) -> str:
    if "$ref" in schema:
        return schema["$ref"].rsplit("/", maxsplit=1)[-1]
    if "anyOf" in schema:
        return " / ".join(schema_type(option) for option in schema["anyOf"])

    data_type = schema.get("type", "object")
    if data_type == "array":
        return f"array[{schema_type(schema.get('items', {}))}]"
    if "enum" in schema:
        values = ", ".join(str(value) for value in schema["enum"])
        return f"{data_type} ({values})"
    return data_type


def render_index() -> str:
    return (
        GENERATED_NOTICE
        + """# ORION Internal Wiki

## Paginas

| Pagina | Fonte autoritativa | Conteudo |
| --- | --- | --- |
| [APIS.md](APIS.md) | FastAPI OpenAPI e rotas WebSocket | endpoints HTTP, schemas e sockets |
| [DATABASE.md](DATABASE.md) | schema SQLite e migrations SQL | tabelas e colunas |
| [PLUGINS.md](PLUGINS.md) | JSON Schema de plugin e manifestos instalados | contrato e inventario seguro |
| [EVENTS.md](EVENTS.md) | `app/events/catalog.py` | eventos compartilhados |

## Politica

A Wiki documenta contratos, nunca valores de runtime. O gerador nao le registros do
banco local, payloads persistidos, chaves, tokens, senhas ou arquivos enviados.
"""
    )


def render_apis() -> str:
    openapi = app.openapi()
    lines = [
        GENERATED_NOTICE,
        "# ORION APIs\n",
        "Fonte: OpenAPI gerado pela aplicacao FastAPI e rotas WebSocket registradas.\n",
        "## HTTP\n",
        "| Metodo | Caminho | Tags | Resumo | Operacao |",
        "| --- | --- | --- | --- | --- |",
    ]

    for path, path_definition in sorted(openapi["paths"].items()):
        for method, operation in sorted(path_definition.items()):
            tags = ", ".join(operation.get("tags", [])) or "-"
            summary = operation.get("summary") or "-"
            operation_id = operation.get("operationId") or "-"
            lines.append(
                f"| `{method.upper()}` | `{path}` | {markdown_cell(tags)} | "
                f"{markdown_cell(summary)} | `{operation_id}` |"
            )

    lines.extend(["", "## WebSocket\n", "| Caminho | Nome |", "| --- | --- |"])
    websocket_routes = [route for route in app.routes if isinstance(route, APIWebSocketRoute)]
    for route in sorted(websocket_routes, key=lambda item: item.path):
        lines.append(f"| `{route.path}` | `{route.name}` |")

    schemas = openapi.get("components", {}).get("schemas", {})
    lines.extend(["", "## Schemas\n"])
    for schema_name, schema in sorted(schemas.items()):
        lines.extend([f"### `{schema_name}`\n", "| Campo | Tipo | Obrigatorio |", "| --- | --- | --- |"])
        required = set(schema.get("required", []))
        for property_name, property_schema in sorted(schema.get("properties", {}).items()):
            lines.append(
                f"| `{property_name}` | `{markdown_cell(schema_type(property_schema))}` | "
                f"{'sim' if property_name in required else 'nao'} |"
            )
        if not schema.get("properties"):
            lines.append("| - | - | - |")
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"


def quote_identifier(identifier: str) -> str:
    return '"' + identifier.replace('"', '""') + '"'


def load_schema_connection() -> sqlite3.Connection:
    connection = sqlite3.connect(":memory:")
    connection.row_factory = sqlite3.Row
    connection.executescript(SCHEMA_PATH.read_text(encoding="utf-8"))
    if MIGRATIONS_PATH.exists():
        for migration_path in sorted(MIGRATIONS_PATH.glob("*.sql")):
            connection.executescript(migration_path.read_text(encoding="utf-8"))
    return connection


def render_database() -> str:
    lines = [
        GENERATED_NOTICE,
        "# ORION Database\n",
        "Fonte: `database/schema.sql` e migrations SQL aplicadas em um SQLite temporario em memoria.\n",
        "O gerador nao abre `database/orion.db` nem le valores persistidos.\n",
        "## Tabelas\n",
        "| Tabela | Colunas |",
        "| --- | --- |",
    ]

    with closing(load_schema_connection()) as connection:
        tables = connection.execute(
            """
            SELECT name, sql
            FROM sqlite_master
            WHERE type = 'table' AND name NOT LIKE 'sqlite_%'
            ORDER BY name
            """
        ).fetchall()
        for table in tables:
            columns = connection.execute(f"PRAGMA table_info({quote_identifier(table['name'])})").fetchall()
            lines.append(f"| `{table['name']}` | {len(columns)} |")

        for table in tables:
            lines.extend(
                [
                    "",
                    f"## `{table['name']}`\n",
                    "| Coluna | Tipo | Nao nulo | Padrao | Chave primaria |",
                    "| --- | --- | --- | --- | --- |",
                ]
            )
            columns = connection.execute(f"PRAGMA table_info({quote_identifier(table['name'])})").fetchall()
            for column in columns:
                lines.append(
                    f"| `{column['name']}` | `{markdown_cell(column['type'])}` | "
                    f"{'sim' if column['notnull'] else 'nao'} | `{markdown_cell(column['dflt_value'])}` | "
                    f"{'sim' if column['pk'] else 'nao'} |"
                )

    return "\n".join(lines).rstrip() + "\n"


def load_installed_plugin_manifests() -> list[dict[str, Any]]:
    manifests = []
    if not INSTALLED_PLUGINS_PATH.exists():
        return manifests

    for manifest_path in sorted(INSTALLED_PLUGINS_PATH.glob("*/plugin.json")):
        manifests.append(json.loads(manifest_path.read_text(encoding="utf-8")))
    return manifests


def render_plugins() -> str:
    plugin_schema = json.loads(PLUGIN_SCHEMA_PATH.read_text(encoding="utf-8"))
    required = set(plugin_schema["required"])
    lines = [
        GENERATED_NOTICE,
        "# ORION Plugins\n",
        "Fonte: `plugins/plugin.schema.json` e manifestos sob `plugins/installed/*/plugin.json`.\n",
        "Carregamento de plugins permanece desabilitado na fundacao atual.\n",
        "## Contrato Do Manifesto\n",
        "| Campo | Tipo | Obrigatorio | Descricao |",
        "| --- | --- | --- | --- |",
    ]

    for field_name, field_schema in plugin_schema["properties"].items():
        lines.append(
            f"| `{field_name}` | `{markdown_cell(schema_type(field_schema))}` | "
            f"{'sim' if field_name in required else 'nao'} | {markdown_cell(field_schema['description'])} |"
        )

    lines.extend(
        [
            "",
            "## Inventario Instalado\n",
            "| ID | Nome | Versao | Autor |",
            "| --- | --- | --- | --- |",
        ]
    )
    manifests = load_installed_plugin_manifests()
    if manifests:
        for manifest in manifests:
            lines.append(
                f"| `{markdown_cell(manifest.get('id'))}` | {markdown_cell(manifest.get('name'))} | "
                f"`{markdown_cell(manifest.get('version'))}` | {markdown_cell(manifest.get('author'))} |"
            )
    else:
        lines.append("| - | Nenhum plugin instalado | - | - |")

    lines.extend(
        [
            "",
            "## Seguranca\n",
            "A Wiki nunca publica assinatura, checksum, permissoes concedidas ou valores de configuracao de plugins.",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_events() -> str:
    lines = [
        GENERATED_NOTICE,
        "# ORION Events\n",
        "Fonte: `app/events/catalog.py`.\n",
        "## Catalogo\n",
        "| Evento | Direcao | Transporte | Persistido | Descricao |",
        "| --- | --- | --- | --- | --- |",
    ]

    for event in EVENT_CATALOG:
        lines.append(
            f"| `{event.name}` | {markdown_cell(event.direction)} | {markdown_cell(event.transport)} | "
            f"{'sim' if event.persisted else 'nao'} | {markdown_cell(event.description)} |"
        )

    for event in EVENT_CATALOG:
        lines.extend(
            [
                "",
                f"## `{event.name}`\n",
                "| Campo | Tipo | Obrigatorio | Descricao |",
                "| --- | --- | --- | --- |",
            ]
        )
        for field in event.fields:
            lines.append(
                f"| `{field.name}` | `{markdown_cell(field.data_type)}` | "
                f"{'sim' if field.required else 'nao'} | {markdown_cell(field.description)} |"
            )

    return "\n".join(lines).rstrip() + "\n"


def render_wiki() -> dict[str, str]:
    return {
        "README.md": render_index(),
        "APIS.md": render_apis(),
        "DATABASE.md": render_database(),
        "PLUGINS.md": render_plugins(),
        "EVENTS.md": render_events(),
    }


def generate_wiki(*, output_dir: Path = WIKI_DIR, check: bool = False) -> list[Path]:
    generated_paths = []
    outdated_paths = []
    for filename, content in render_wiki().items():
        output_path = output_dir / filename
        generated_paths.append(output_path)
        if check:
            if not output_path.exists() or output_path.read_text(encoding="utf-8") != content:
                outdated_paths.append(output_path)
            continue

        output_dir.mkdir(parents=True, exist_ok=True)
        output_path.write_text(content, encoding="utf-8")

    if outdated_paths:
        relative_paths = ", ".join(str(path.relative_to(ROOT)) for path in outdated_paths)
        raise WikiOutdatedError(f"Generated Wiki is outdated: {relative_paths}")
    return generated_paths


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="Fail when committed Wiki pages are outdated.")
    args = parser.parse_args()

    try:
        generated_paths = generate_wiki(check=args.check)
    except WikiOutdatedError as exc:
        raise SystemExit(str(exc)) from exc

    action = "checked" if args.check else "generated"
    print(f"Wiki {action}: {len(generated_paths)} pages")


if __name__ == "__main__":
    main()
